name: 'Setup Dart & Node'
description: 'Setup Dart SDK, Node.js, and restore cache'

inputs:
  dart-version:
    description: 'Dart SDK version'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: ${{ inputs.dart-version }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Cache Dart packages
      uses: actions/cache@v4
      with:
        path: ~/.pub-cache
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: ${{ runner.os }}-pub-

    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json', '**/package.json') }}
        restore-keys: ${{ runner.os }}-node-
