name: 'Test with Coverage'
description: 'Run dart tests with coverage check'

inputs:
  working-directory:
    description: 'Directory to run tests in'
    required: true
  min-coverage:
    description: 'Minimum coverage percentage'
    required: true
  name:
    description: 'Name for logging'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Test ${{ inputs.name }} with coverage
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        dart test --coverage=coverage
        dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib
        COVERAGE=$(awk -F: '/^LF:/ { total += $2 } /^LH:/ { covered += $2 } END { if (total > 0) printf "%.1f", (covered / total) * 100; else print "0" }' coverage/lcov.info)
        echo "${{ inputs.name }} coverage: ${COVERAGE}%"
        if [ -z "$COVERAGE" ] || [ "$COVERAGE" = "0" ] || [ "$(echo "$COVERAGE < ${{ inputs.min-coverage }}" | bc -l)" -eq 1 ]; then
          echo "Coverage ${COVERAGE}% is below ${{ inputs.min-coverage }}% threshold"
          exit 1
        fi
